language: node_js
node_js:
  - '4'
  - '5'
  - '6'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libudev-dev
  - npm install -g gulp
script:
  - npm run lint
  - npm run test
after_success:
  - npm run coveralls
